name: DevSecOps Pipeline


on:
    push:
        branches:
            - main


jobs:
    security:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action
              env:
                SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

            - name: Build Docker Image
              run: docker build -t myapp .

            - name: Wiz Scan
              run: echo "Scanning image"

            - name: Deploy
              run: echo "Deploying"
